#!/usr/bin/sh

sxhkd &
picom -fb &
polybar &
dunst &
betterlockscreen -w dim &
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5

bspc config border_width        3
bspc config window_gap          10
bspc config focused_border_color "#a3be8c"
bspc config normal_border_color "#8fcbb"
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

